language: go

go:
  - "1.11.4"

install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - make tools

go_import_path: github.com/aslakknutsen/istio-workspace

script:
  - make
